### ISSUE TITLE
Avaliability

### ISSUE THREAD

**Issue by matifol** [demyte/language-cshtml#1]
Great package @demyte !
Just wondering, why isn't it available directly from atom?

**Comment by demyte** [comment]
Hi @matifol 

Thanks for the feedback!

I am not sure why you may not be seeing it through Atom as I am pretty sure it is published and available.
  https://atom.io/packages/language-cshtml

When I search for it in "Install" in the Atom options, it comes up for me.

Maybe you can try and Star the package on the page above and then on your machine use:
   apm stars --install
 or just directly install it with:
   apm install language-cshtml

**Comment by matifol** [comment]
It pops up in "Install" for me now as well, tho I'm not entirely sure why :-)
Anyway, I ended up running `apm install language-cshtml`. Worked like a charm. Thanks a lot for your quick response and help!
