### ISSUE TITLE
[ini] Language Colorize working incorrectly for INI files

### ISSUE THREAD

**Issue by aeschli** [demyte/language-cshtml#11]
_From @hcoona on July 4, 2016 6:43_

- VSCode Version: v1.2.1
- OS Version: Windows 10

Steps to Reproduce:
1. Change file type to INI
2. type "A=b;xxxx" in file content

Expected: "b;xxxx" colored as white
Actual: "b" in white but ";xxxx" in green

";xxxx" should only be regard as comments when there is no other contents in the line before ";"

_Copied from original issue: Microsoft/vscode#8709_

**Comment by demyte** [comment]
Closing as I do not believe this is relevant for this grammar

**Comment by hcoona** [comment]
I would suggest to move it to the correct place & reopen it there.
