### ISSUE TITLE
[ini] syntax highlighting not working with arrays

### ISSUE THREAD

**Issue by mastazi** [demyte/language-cshtml#13]
_Preamble: posting here because I have seen that other issues with .ini syntax highlighting in VS Code have been moved to this repo, e.g._ https://github.com/demyte/language-cshtml/issues/11 _if this is not the correct place to post, I aplogise, please feel free to move it elsewhere._

In VS Code, when editing .ini files, arrays are not highlighted.

How to reproduce:

open VS Code
create a file with extension .ini
add to the file an array, e.g. 

    mylabel[myindex] = myvalue
    mylabel[otherindex] = othervalue

the lines are not colorized.

**Comment by demyte** [comment]
Closing as I do not believe this is valid for this grammar
