### ISSUE TITLE
Syntax highlighting breaking after missing semicolon

### ISSUE THREAD

**Issue by grantwhiting** [demyte/language-cshtml#14]
When editing a .cshtml file my syntax highlighting is breaking if I don't put a semicolon after every Razor reference. The semicolons aren't required and frankly shouldn't be there anyway. I have the language-cshtml package installed.

Missing semicolon:
![image](https://user-images.githubusercontent.com/24999561/26847184-fe3916f0-4ab0-11e7-8a4f-e711c5d4e81c.png)

With semicolon:
![image](https://user-images.githubusercontent.com/24999561/26847216-130c4156-4ab1-11e7-9b91-25b2240a4838.png)

**Comment by m-hagberg** [comment]
I'm experiencing the same issue, and it's making my job quite annoying.
 
![screen shot 2017-06-19 at 09 56 56](https://user-images.githubusercontent.com/12826090/27274982-bb8bde3a-54d5-11e7-89e4-30f78cd77b81.png)

I can "fix" this issue temporarily by adding semicolons - however, as you may see from my code, the semicolons are in these cases printed onto the end-user page, which is less than ideal.

**Comment by m-hagberg** [comment]
I wrote a small regex that _should_ work, but unfortunately doesn't. I've never written plugins before, so there might be something else I'm missing.

The regex I tried was:

```cson
"end": "(\\s|;|(\\(.*\\)(;)*))"
```
at [cshtml.cson:L85](https://github.com/demyte/language-cshtml/blob/master/grammars/cshtml.cson#L85), and it would replace the current `"end": "(\\n|\\s)"`.

The pattern in it's entirety would then be
```regexp
(@[a-zA-Z0-9]+)(\s?)(([a-zA-Z0-9]+)(\.)?)+?(\s|;|(\(.*\)(;)*))
```
which I've tested on [regexr.com](http://regexr.com), but alas doesn't work in Atom. Any ideas, @demyte?

**Comment by demyte** [comment]
Hi @m-hagberg 

I haven't used atom for a long time as I moved over to VSCode.

I have just downloaded Atom and will see if I can get this fixed in the next day or so.

**Comment by demyte** [comment]
I have just pushed out a release v0.3.0 that addresses this issue.
